# Port number of javaBE server
server.port: 8081

# API city service api-ninjas.com URL
cityUrl: "https://api.api-ninjas.com/v1/city?name="

# API key of the city service api-ninjas.com
apiKey: "C1t26Ch1x8ajTwcwiZb2OA==SbUTy8kkFiQ4t2Zd"

# API weather service open-meteo.com URL
weatherUrl: "https://api.open-meteo.com/v1/forecast?"